/**
 * Home Health Outlook Copy Governance
 * 
 * Single source of truth for all Home Health Outlook copy.
 * Enforces product doctrine with explicit banned phrase validation.
 * 
 * PRODUCT DOCTRINE:
 * - The score is always explainable by systems below it
 * - X → Y means: "If current assumptions remain unchanged, this is the expected directional shift"
 * - Contributor levels are interpretive, not mathematical
 * - Costs belong after understanding, not before (only in Trajectories section)
 */

// ============== Types ==============

/** Contributor level (interpretive, not mathematical) */
export type ContributorLevel = 'primary' | 'moderate' | 'minor';

/** Climate context with explicit semantics */
export type ClimateContextType = 
  | 'south_florida'    // High heat, humidity, UV exposure
  | 'coastal'          // Salt air, corrosion risk
  | 'freeze_thaw'      // Ice, foundation stress
  | 'temperate';       // Standard wear patterns

/** Install source for causality descriptions */
export type InstallSourceType = 'permit' | 'inferred' | 'unknown';

/** Lifecycle position */
export type LifecyclePosition = 'early' | 'mid' | 'late' | 'end';

/** System keys */
export type SystemKey = 'hvac' | 'roof' | 'water_heater';

/** System influence for causality section */
export interface SystemInfluence {
  systemKey: SystemKey;
  displayName: string;
  contributorLevel: ContributorLevel;
  description: string; // Plain English causality (generated by deriveInfluenceDescription)
}

/** Full copy contract */
export interface HomeHealthOutlookCopy {
  header: string;
  scoreSubtext: string;
  causalitySectionTitle: string;
  trajectoriesSectionTitle: string;
  trajectoriesSectionSubhead: string;
  legendLabels: Record<ContributorLevel, string>;
  interactionCopy: {
    whyThisMatters: string;
    stabilizeHint: string;
  };
  tooltipRefinements: {
    estimatedSource: string;
    observedWindow: string;
  };
  fallbackCopy: {
    limitedInfoNote: string;
  };
}

// ============== Banned Phrases ==============

/**
 * These phrases are explicitly prohibited in any outlook copy.
 * Violation of this list breaks user trust.
 */
export const BANNED_PHRASES = [
  'If left untracked',
  'Without Habitta',
  'With Habitta',
  'Prevent failure',
  'Avoid disaster',
  'Your home will',
  'points',
  '24-Month Outlook',
  'failing',
  'urgent',
  'critical',
  'immediately',
] as const;

/**
 * Validate that copy doesn't contain banned phrases.
 * Used for runtime validation in development.
 */
export function validateCopy(copy: string): { valid: boolean; violations: string[] } {
  const violations = BANNED_PHRASES.filter(phrase => 
    copy.toLowerCase().includes(phrase.toLowerCase())
  );
  return { valid: violations.length === 0, violations };
}

// ============== Static Copy ==============

/**
 * Get static copy for the outlook module.
 */
export function getHomeHealthOutlookCopy(): HomeHealthOutlookCopy {
  return {
    header: 'Home Health',
    scoreSubtext: 'This outlook reflects system age, climate exposure, and current maintenance visibility.',
    causalitySectionTitle: "What's influencing this outlook",
    trajectoriesSectionTitle: 'System Trajectories',
    trajectoriesSectionSubhead: 'These systems shape how your home\'s health evolves over time.',
    legendLabels: {
      primary: 'Meaningfully affects overall home health trajectory',
      moderate: 'Gradual influence',
      minor: 'Limited near-term impact',
    },
    interactionCopy: {
      whyThisMatters: 'This system is currently influencing your home\'s projected health trend due to its age and verification status.',
      stabilizeHint: 'Updating maintenance history or install details can stabilize this outlook.',
    },
    tooltipRefinements: {
      estimatedSource: 'Based on permits, records, and regional averages',
      observedWindow: 'Observed replacement window',
    },
    fallbackCopy: {
      limitedInfoNote: 'Limited information available. Estimates will improve as details are added.',
    },
  };
}

// ============== System Display Names ==============

const SYSTEM_DISPLAY_NAMES: Record<SystemKey, string> = {
  hvac: 'HVAC System',
  roof: 'Roof',
  water_heater: 'Water Heater',
};

// ============== Contributor Level Derivation ==============

/**
 * Determines contributor level using heuristic judgment,
 * not strict point math. May be overridden by climate stress
 * or lifecycle signals.
 * 
 * Thresholds are NOT absolute:
 * - Primary: remainingYears <= 5 AND confidence > 0.5
 * - Moderate: remainingYears <= 10 OR (remainingYears <= 7 AND confidence < 0.5)
 * - Minor: remainingYears > 10
 * 
 * Climate stress can elevate a system by one level.
 * Lifecycle position can also override (end-of-life → at least moderate).
 */
export function deriveContributorLevel(
  remainingYears: number,
  confidence: number,
  lifecyclePosition?: LifecyclePosition,
  climateContext?: ClimateContextType
): ContributorLevel {
  // End-of-life always at least moderate
  if (lifecyclePosition === 'end') {
    if (remainingYears <= 3) return 'primary';
    return 'moderate';
  }

  // Base level from remaining years and confidence
  let baseLevel: ContributorLevel = 'minor';
  
  if (remainingYears <= 5 && confidence > 0.5) {
    baseLevel = 'primary';
  } else if (remainingYears <= 10 || (remainingYears <= 7 && confidence < 0.5)) {
    baseLevel = 'moderate';
  }

  // Climate stress can elevate by one level (not above primary)
  const highStressClimates: ClimateContextType[] = ['south_florida', 'coastal'];
  if (climateContext && highStressClimates.includes(climateContext)) {
    if (baseLevel === 'minor') return 'moderate';
    if (baseLevel === 'moderate') return 'primary';
  }

  // Late lifecycle elevates to at least moderate
  if (lifecyclePosition === 'late' && baseLevel === 'minor') {
    return 'moderate';
  }

  return baseLevel;
}

// ============== Influence Description Generation ==============

/**
 * Generate plain English causality description for a system.
 * No timelines, no costs, no urgent verbs.
 */
export function deriveInfluenceDescription(
  systemKey: SystemKey,
  installSource: InstallSourceType,
  lifecyclePosition: LifecyclePosition,
  hasRecentService: boolean,
  climateContext?: ClimateContextType
): string {
  const parts: string[] = [];

  // Lifecycle position
  const positionLabels: Record<LifecyclePosition, string> = {
    early: 'Early lifecycle',
    mid: 'Mid-lifecycle',
    late: 'Late lifecycle',
    end: 'End of expected lifecycle',
  };
  parts.push(positionLabels[lifecyclePosition]);

  // Install source context
  if (installSource === 'permit') {
    parts.push('Install date verified from permits');
  } else if (installSource === 'inferred') {
    parts.push('Install date inferred from permits and regional patterns');
  } else {
    parts.push('Install date unverified');
  }

  // Service history
  if (!hasRecentService) {
    parts.push('No recent service activity observed');
  }

  // Climate context (system-specific)
  if (climateContext) {
    const climateDescriptions: Record<ClimateContextType, Record<SystemKey, string>> = {
      south_florida: {
        hvac: 'Operating under sustained heat and humidity',
        roof: 'Aging under sustained South Florida heat, UV, and moisture exposure',
        water_heater: 'Higher corrosion risk from humidity',
      },
      coastal: {
        hvac: 'Salt air exposure increases wear',
        roof: 'Salt air accelerates surface degradation',
        water_heater: 'Coastal humidity affects tank longevity',
      },
      freeze_thaw: {
        hvac: 'Freeze-thaw cycles stress outdoor components',
        roof: 'Ice dam risk during winter months',
        water_heater: 'Pipe insulation condition affects efficiency',
      },
      temperate: {
        hvac: 'Operating under typical seasonal conditions',
        roof: 'Standard wear patterns expected',
        water_heater: 'Standard wear patterns expected',
      },
    };
    const desc = climateDescriptions[climateContext]?.[systemKey];
    if (desc && climateContext !== 'temperate') {
      parts.push(desc);
    }
  }

  // Join with periods for inspector-style prose
  return parts.join('. ') + '.';
}

// ============== Full Influence Builder ==============

/**
 * Build a complete SystemInfluence object from raw data.
 */
export function buildSystemInfluence(
  systemKey: SystemKey,
  installSource: InstallSourceType,
  lifecyclePosition: LifecyclePosition,
  hasRecentService: boolean,
  remainingYears: number,
  confidence: number,
  climateContext?: ClimateContextType
): SystemInfluence {
  return {
    systemKey,
    displayName: SYSTEM_DISPLAY_NAMES[systemKey],
    contributorLevel: deriveContributorLevel(remainingYears, confidence, lifecyclePosition, climateContext),
    description: deriveInfluenceDescription(systemKey, installSource, lifecyclePosition, hasRecentService, climateContext),
  };
}

/**
 * Sort influences by contributor level (primary first)
 */
export function sortInfluencesByPriority(influences: SystemInfluence[]): SystemInfluence[] {
  const priorityOrder: Record<ContributorLevel, number> = {
    primary: 0,
    moderate: 1,
    minor: 2,
  };
  return [...influences].sort((a, b) => 
    priorityOrder[a.contributorLevel] - priorityOrder[b.contributorLevel]
  );
}
